backend:
  name: github
  repo: SkyClerik/dwarf-clash-decap-cms-wiki
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "pages"
    label: "Страницы"
    folder: "_pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Текст", name: "body", widget: "markdown"}