backend:
  name: github
  repo: SkyClerik/dwarf-clash-decap-cms-wiki
  branch: main
  site_domain: guileless-fudge-4d7b03.netlify.app

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "pages"
    label: "Страницы"
    folder: "_pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Заголовок", name: "title", widget: "string" }
      - { label: "Текст", name: "body", widget: "markdown" }